#!/bin/bash

RunNum=$1
DAQ_SESSION=$2
Experiment=$3

SCRIPT_DIR=/home/cdaq/rcdb/hallcdb/scripts/daq
RunLogFile=/home/hccoda/coda/cool/${DAQ_SESSION}/ddb/run-log/${Experiment}/current_run.log

if [[ -z "$RCDB_CONNECTION" ]]; then
    source ${SCRIPT_DIR}/../../setup.sh
fi    

# Run the script
python ${SCRIPT_DIR}/update.py --run=${RunNum} --daq=${DAQ_SESSION} --logfile=${RunLogFile} --update=coda,epics --reason=end --exp=${Experiment}

# legacy scripts
#python ${SCRIPT_DIR}/run_end.py ${RunLogFile} --run=${RunNum}
#python ${SCRIPT_DIR}/run_end.py ${RunLogFile} 
