#!/bin/bash

RunNum=$1
Session=$2

SCRIPT_DIR=/home/cdaq/rcdb/hallcdb/scripts

if [[ -z "$RCDB_CONNECTION" ]]; then
    source ${SCRIPT_DIR}/../setup.sh
fi    

# Run the script 
python3 ${SCRIPT_DIR}/run_start.py --run=${RunNum} --daq=${Session} --update=epics,coda --reason=start
#python3 ${SCRIPT_DIR}/run_start.py --run=${RunNum} --daq=${Session} --update=epics,coda --reason=start --test=True

